# Generated by Django 5.1.3 on 2024-11-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proforma', '0017_alter_proformapayment_payer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot_number', models.IntegerField()),
                ('cot_date', models.DateField()),
                ('total_value', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customs_value', models.BigIntegerField()),
                ('import_rights', models.BigIntegerField()),
                ('red_cersent', models.BigIntegerField()),
                ('added_value', models.BigIntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('currency_price', models.IntegerField()),
                ('other_expense', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proforma.performa')),
            ],
        ),
    ]
