# Generated by Django 5.1.3 on 2024-11-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0001_initial'),
        ('proforma', '0017_alter_proformapayment_payer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='cot_date',
            new_name='cottage_date',
        ),
        migrations.RenameField(
            model_name='cottage',
            old_name='cot_number',
            new_name='cottage_number',
        ),
        migrations.AlterField(
            model_name='cottage',
            name='added_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='currency_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='customs_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='import_rights',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='other_expense',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottages', to='proforma.performa'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='red_cersent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
