# Generated by Django 5.1.3 on 2024-11-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0002_rename_cot_date_cottage_cottage_date_and_more'),
        ('proforma', '0018_alter_performa_prf_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottages', to='proforma.performa', to_field='prf_order_no'),
        ),
    ]
