# Generated by Django 5.1.3 on 2024-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0003_alter_cottage_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='hhhg',
            field=models.DecimalField(blank=True, decimal_places=2, default=123, editable=False, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cottage',
            name='riali',
            field=models.DecimalField(blank=True, decimal_places=2, default=123, editable=False, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cottage',
            name='currency_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='final_price',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='other_expense',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='red_cersent',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
