# Generated by Django 5.1.3 on 2024-11-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0004_cottage_hhhg_cottage_riali_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='added_value',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='customs_value',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='hhhg',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='import_rights',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='other_expense',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='red_cersent',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='riali',
        ),
        migrations.CreateModel(
            name='CottageGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('import_rights', models.DecimalField(decimal_places=2, max_digits=20)),
                ('red_cersent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('added_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('riali', models.IntegerField(blank=True, default=0, editable=False)),
                ('hhhg', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20)),
                ('other_expense', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20)),
                ('final_price', models.IntegerField(blank=True, default=0, editable=False)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottage.cottage')),
            ],
        ),
    ]
