# Generated by Django 5.1.3 on 2024-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0005_remove_cottage_added_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottagegoods',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=1244, max_digits=15),
            preserve_default=False,
        ),
    ]
