# Generated by Django 5.1.3 on 2024-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0006_cottagegoods_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottagegoods',
            name='hscode',
            field=models.CharField(default=123442, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
