# Generated by Django 5.1.3 on 2024-11-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0007_cottagegoods_hscode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottagegoods',
            old_name='hscode',
            new_name='goodscode',
        ),
    ]
