# Generated by Django 5.1.3 on 2024-11-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0008_rename_hscode_cottagegoods_goodscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottagegoods',
            name='quantity',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cottage',
            name='cottage_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='currency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cottagegoods',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottage_goods', to='cottage.cottage'),
        ),
    ]
