# Generated by Django 5.1.3 on 2024-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0009_cottagegoods_quantity_alter_cottage_cottage_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottagegoods',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
