# Generated by Django 5.1.3 on 2024-11-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0010_alter_cottagegoods_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottagegoods',
            name='goods_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
