# Generated by Django 5.1.3 on 2024-11-30 10:42

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0011_cottagegoods_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='cottage_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
