# Generated by Django 5.1.3 on 2024-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0012_alter_cottage_cottage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='cottage_status',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cottage',
            name='rafee_taahod',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
