# Generated by Django 5.1.3 on 2024-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0013_cottage_cottage_status_cottage_rafee_taahod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='rafee_taahod',
            field=models.BooleanField(default=False),
        ),
    ]
