# Generated by Django 5.1.3 on 2024-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0014_alter_cottage_rafee_taahod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='docs_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cottage',
            name='rewatch',
            field=models.BooleanField(default=False),
        ),
    ]
