# Generated by Django 5.1.3 on 2024-12-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0015_cottage_docs_recieved_cottage_rewatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='cottage_customer',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
