# Generated by Django 5.1.3 on 2024-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0016_cottage_cottage_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
