# Generated by Django 5.1.3 on 2024-12-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0017_cottage_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedCottages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cottage_number', models.CharField(max_length=55)),
                ('cottage_date', models.CharField(max_length=55)),
                ('cottage_value', models.CharField(max_length=55)),
                ('cottage_currency', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='cottage',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
