# Generated by Django 5.1.3 on 2024-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0018_exportedcottages_alter_cottage_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='exceeded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
