# Generated by Django 5.1.3 on 2024-12-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0019_cottage_exceeded_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='exceeded_amount',
        ),
    ]
