# Generated by Django 5.1.3 on 2024-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0020_remove_cottage_exceeded_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottagegoods',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
