# Generated by Django 5.1.3 on 2024-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0021_alter_cottagegoods_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottagegoods',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottagegoods',
            name='riali',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20),
        ),
    ]
