# Generated by Django 5.1.3 on 2024-12-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0022_alter_cottagegoods_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottagegoods',
            name='other_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
