# Generated by Django 5.1.3 on 2024-12-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0023_alter_cottagegoods_other_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportedCottages',
        ),
        migrations.AlterField(
            model_name='cottagegoods',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
