# Generated by Django 5.1.3 on 2024-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0024_delete_exportedcottages_alter_cottagegoods_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='refrence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
