# Generated by Django 5.1.3 on 2024-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0025_cottage_refrence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='refrence_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
