# Generated by Django 5.1.3 on 2024-12-30 11:39

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0026_alter_cottage_refrence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedCottages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_serial_number', models.CharField(unique=True)),
                ('cottage_number', models.CharField(unique=True)),
                ('cottage_date', django_jalali.db.models.jDateField()),
                ('refrence_number', models.CharField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('currency_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cottage_customer', models.CharField(blank=True, max_length=55, null=True)),
                ('cottage_status', models.CharField(blank=True, max_length=55, null=True)),
                ('rafee_taahod', models.BooleanField(default=False)),
                ('docs_recieved', models.BooleanField(default=False)),
                ('rewatch', models.BooleanField(default=False)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
