# Generated by Django 5.1.3 on 2024-12-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0027_exportedcottages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportedcottages',
            old_name='cottage_customer',
            new_name='declaration_status',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='cottage_status',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='docs_recieved',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='rafee_taahod',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='refrence_number',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='rewatch',
        ),
    ]
