# Generated by Django 5.1.3 on 2024-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0028_rename_cottage_customer_exportedcottages_declaration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedcottages',
            name='currency_type',
            field=models.CharField(default='USD', max_length=55),
        ),
    ]
