# Generated by Django 5.1.3 on 2024-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0029_exportedcottages_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedcottages',
            name='cottage_number',
            field=models.IntegerField(unique=True),
        ),
    ]
