# Generated by Django 5.1.3 on 2024-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0030_alter_exportedcottages_cottage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedcottages',
            name='remaining_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
