# Generated by Django 5.1.3 on 2025-01-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0031_exportedcottages_remaining_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedcottages',
            name='cottage_date',
            field=models.CharField(max_length=55),
        ),
    ]
