# Generated by Django 5.1.3 on 2025-01-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0032_alter_exportedcottages_cottage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedcottages',
            name='customs_code',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
