# Generated by Django 5.1.3 on 2025-01-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0033_exportedcottages_customs_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportedcottages',
            name='cottage_number',
        ),
        migrations.RemoveField(
            model_name='exportedcottages',
            name='customs_code',
        ),
    ]
