# Generated by Django 5.1.3 on 2025-01-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0034_remove_exportedcottages_cottage_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottage',
            options={'ordering': ['-cottage_date']},
        ),
    ]
