# Generated by Django 5.1.3 on 2025-01-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_costumer_full_name'),
        ('cottage', '0035_alter_cottage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportedcottages',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='cottage',
            name='cottage_customer',
            field=models.ForeignKey(blank=True, max_length=55, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costumer', to_field='full_name'),
        ),
    ]
