# Generated by Django 5.1.3 on 2025-01-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0038_alter_cottage_cottage_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='cottage_customer',
        ),
    ]
