# Generated by Django 5.1.3 on 2025-01-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_costumer_full_name'),
        ('cottage', '0039_remove_cottage_cottage_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='cottage_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costumer'),
        ),
    ]
