# Generated by Django 5.1.3 on 2025-02-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0040_cottage_cottage_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottagegoods',
            options={'ordering': ['-cottage__cottage_date']},
        ),
    ]
