# Generated by Django 5.1.3 on 2025-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0041_alter_cottagegoods_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='Intermediary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
