# Generated by Django 5.1.3 on 2025-05-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0042_cottage_intermediary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
