# Generated by Django 5.1.3 on 2025-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0043_cottage_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='customs_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True),
        ),
    ]
