# Generated by Django 5.1.3 on 2025-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0044_cottage_customs_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='added_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
