# Generated by Django 5.1.3 on 2025-07-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0045_cottage_added_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cottage.cottage')),
            ],
        ),
    ]
