# Generated by Django 5.1.3 on 2025-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0046_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('TRY', 'Turkish Lira')], default='IRR', max_length=10),
        ),
    ]
