# Generated by Django 5.1.3 on 2025-07-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0047_expenses_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='currency',
        ),
    ]
