# Generated by Django 5.1.3 on 2025-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0048_remove_expenses_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='total_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
