# Generated by Django 5.1.3 on 2025-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0049_cottage_total_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='customs_value_epl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True),
        ),
    ]
