# Generated by Django 5.1.3 on 2024-11-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prf_number', models.CharField(max_length=255)),
                ('prf_date', models.DateTimeField()),
                ('prf_expire_date', models.DateTimeField()),
                ('prf_total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prf_currency_type', models.CharField(max_length=50)),
                ('prf_seller_name', models.CharField(max_length=255)),
                ('prf_seller_country', models.CharField(max_length=100)),
                ('prf_order_no', models.CharField(max_length=100)),
                ('prf_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prfctm_name', models.CharField(max_length=255)),
                ('prfctm_code', models.CharField(max_length=50)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='proforma.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_status', models.CharField(max_length=50)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_email', models.EmailField(max_length=254)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='proforma.proforma')),
            ],
        ),
    ]
