# Generated by Django 5.1.3 on 2024-11-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant', models.CharField(max_length=255)),
                ('prf_vcode_int', models.BigIntegerField()),
                ('prf_number_str', models.CharField(max_length=50)),
                ('prf_date', models.DateTimeField()),
                ('prf_expire_date', models.DateTimeField()),
                ('prf_status_str', models.CharField(max_length=50)),
                ('prf_currency_type_str', models.CharField(max_length=50)),
                ('prf_total_price_mny', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prf_freight_cost_mny', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='proformadetail',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='proforma.performa'),
        ),
        migrations.AlterField(
            model_name='proformapayment',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='proforma.performa'),
        ),
        migrations.DeleteModel(
            name='Proforma',
        ),
    ]
