# Generated by Django 5.1.3 on 2024-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0002_performa_alter_proformadetail_proforma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performa',
            name='prf_currency_type_str',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_date',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_expire_date',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_freight_cost_mny',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_number_str',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_status_str',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_total_price_mny',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='prf_vcode_int',
        ),
        migrations.RemoveField(
            model_name='performa',
            name='registrant',
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_currency_type',
            field=models.CharField(default='asd', max_length=10),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_number',
            field=models.CharField(default='asd', max_length=100),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_order_no',
            field=models.CharField(default='asd', max_length=100),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_seller_country',
            field=models.CharField(default='asd', max_length=255),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_seller_name',
            field=models.CharField(default='asd', max_length=255),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_status',
            field=models.CharField(default='asd', max_length=50),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
