# Generated by Django 5.1.3 on 2024-11-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0003_remove_performa_prf_currency_type_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='prf_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
