# Generated by Django 5.1.3 on 2024-11-06 08:34

import proforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0004_performa_prf_date_performa_prf_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_currency_type',
            field=models.IntegerField(default=proforma.models.get_default_currency_type),
        ),
    ]
