# Generated by Django 5.1.3 on 2024-11-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0005_alter_performa_prf_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_total_price',
            field=models.CharField(default='asd', max_length=100),
        ),
    ]
