# Generated by Django 5.1.3 on 2024-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0006_alter_performa_prf_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_currency_type',
            field=models.CharField(default='asd', max_length=100),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
