# Generated by Django 5.1.3 on 2024-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0007_alter_performa_prf_currency_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='prfVCodeInt',
            field=models.CharField(default=1234124, max_length=50),
            preserve_default=False,
        ),
    ]
