# Generated by Django 5.1.3 on 2024-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0008_performa_prfvcodeint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prfVCodeInt',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_number',
            field=models.CharField(default='asd', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
