# Generated by Django 5.1.3 on 2024-11-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0009_alter_performa_prfvcodeint_alter_performa_prf_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_datetime', models.DateTimeField()),
                ('new_active_status', models.CharField(blank=True, max_length=100, null=True)),
                ('new_status', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('permit_request_code', models.BigIntegerField(blank=True, null=True)),
                ('performa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_statuses', to='proforma.performa')),
            ],
        ),
    ]
