# Generated by Django 5.1.3 on 2024-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0010_requeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='ssdsshGUID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
