# Generated by Django 5.1.3 on 2024-11-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0011_performa_ssdsshguid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformadetail',
            old_name='proforma',
            new_name='performa',
        ),
    ]
