# Generated by Django 5.1.3 on 2024-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0013_alter_performa_prf_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_order_no',
            field=models.CharField(default='asd', max_length=100),
        ),
    ]
