# Generated by Django 5.1.3 on 2024-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0014_alter_performa_prf_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformadetail',
            name='prfcntVCodeStr',
            field=models.CharField(default='abcd', max_length=50),
        ),
    ]
