# Generated by Django 5.1.3 on 2024-11-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0015_proformadetail_prfcntvcodestr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststatus',
            old_name='new_status',
            new_name='agn_name_str',
        ),
        migrations.RenameField(
            model_name='requeststatus',
            old_name='message',
            new_name='fld_desc_str',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='change_datetime',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='new_active_status',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='permit_request_code',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='version',
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='agn_vcode_int',
            field=models.BigIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='gds_hs_code',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='pfg_commercial_desc_str',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='pfg_status_criteria_inquiry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='pfg_status_result_request_sabtaresh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='pfg_vcode_lng',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='pgp_description_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='pgp_send_status_tny',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
