# Generated by Django 5.1.3 on 2024-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0016_rename_new_status_requeststatus_agn_name_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformapayment',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proformapayment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proformapayment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
