# Generated by Django 5.1.3 on 2024-11-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0017_alter_proformapayment_payer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_order_no',
            field=models.CharField(default='asd', max_length=100, unique=True),
        ),
    ]
