# Generated by Django 5.1.3 on 2024-11-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0018_alter_performa_prf_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performa',
            name='ssdsshGUID',
        ),
    ]
