# Generated by Django 5.1.3 on 2024-11-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0019_remove_performa_ssdsshguid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformapayment',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='performa',
        ),
        migrations.DeleteModel(
            name='ProformaDetail',
        ),
        migrations.DeleteModel(
            name='ProformaPayment',
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
    ]
