# Generated by Django 5.1.3 on 2024-12-03 10:58

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0020_remove_proformapayment_proforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_expire_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
