# Generated by Django 5.1.3 on 2024-12-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0021_alter_performa_prf_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='remaining_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
