# Generated by Django 5.1.3 on 2024-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0022_performa_remaining_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='exceeded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
