# Generated by Django 5.1.3 on 2024-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0023_performa_exceeded_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performa',
            name='exceeded_amount',
        ),
        migrations.AddField(
            model_name='performa',
            name='FOB',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_freight_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
