# Generated by Django 5.1.3 on 2024-12-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0024_remove_performa_exceeded_amount_performa_fob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='FOB',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_freight_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
