# Generated by Django 5.1.3 on 2024-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0025_alter_performa_fob_alter_performa_prf_freight_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performa',
            name='prf_seller_name',
        ),
        migrations.AddField(
            model_name='performa',
            name='registrant',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
