# Generated by Django 5.1.3 on 2025-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0026_remove_performa_prf_seller_name_performa_registrant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performa',
            options={'ordering': ['-prf_date']},
        ),
        migrations.AddField(
            model_name='performa',
            name='prf_currency_price',
            field=models.PositiveIntegerField(blank=True, max_length=8, null=True),
        ),
    ]
