# Generated by Django 5.1.3 on 2025-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0027_alter_performa_options_performa_prf_currency_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='bank_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='performa',
            name='goods_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performa',
            name='payment_instrument',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performa',
            name='purchased_total',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='performa',
            name='rial_deposit',
            field=models.BigIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='prf_currency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
