# Generated by Django 5.1.3 on 2025-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0028_performa_bank_info_performa_goods_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='prf_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
