# Generated by Django 5.1.3 on 2025-05-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0029_alter_performa_prf_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='booked_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
