# Generated by Django 5.1.3 on 2025-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0030_performa_booked_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='remaining_freight_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
