# Generated by Django 5.1.3 on 2025-01-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('goods_name_fa', models.TextField(max_length=255)),
                ('goods_name_en', models.TextField(max_length=255)),
                ('profit', models.IntegerField()),
                ('customs_duty_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('SUQ', models.CharField(choices=[('1000kwh', '1000Kwh'), ('1000u', '1000U'), ('2u', '2U'), ('c', 'C'), ('carat', 'Carat'), ('kg', 'Kg'), ('l', 'L'), ('m', 'M'), ('m2', 'M2'), ('m3', 'M3'), ('mm', 'Mm'), ('u', 'U')], default='u', max_length=20)),
                ('tags', models.ManyToManyField(to='customs.tag')),
            ],
        ),
    ]
