# Generated by Django 5.1.3 on 2025-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscode',
            name='goods_name_en',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='goods_name_fa',
            field=models.TextField(max_length=1000),
        ),
    ]
