# Generated by Django 5.1.3 on 2025-01-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_alter_hscode_goods_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscode',
            name='SUQ',
            field=models.CharField(choices=[('1000kwh', '1000Kwh'), ('1000u', '1000U'), ('2u', '2U'), ('c', 'C'), ('carat', 'Carat'), ('Kg', 'Kg'), ('l', 'L'), ('m', 'M'), ('m2', 'M2'), ('m3', 'M3'), ('mm', 'Mm'), ('U', 'U')], default='u', max_length=20),
        ),
    ]
