# Generated by Django 5.1.3 on 2025-01-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0003_alter_hscode_suq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hscode',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='hscode',
            name='SUQ',
            field=models.CharField(choices=[('1000kwh', '1000Kwh'), ('1000u', '1000U'), ('2U', '2U'), ('c', 'C'), ('Carat', 'Carat'), ('Kg', 'Kg'), ('L', 'L'), ('m', 'M'), ('m2', 'M2'), ('m3', 'M3'), ('mm', 'Mm'), ('U', 'U')], default='u', max_length=20),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='customs_duty_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
