# Generated by Django 5.1.3 on 2025-01-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0004_alter_hscode_options_alter_hscode_suq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hscode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hscodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hscode',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
