# Generated by Django 5.1.3 on 2025-01-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0006_heading_subheading_hscode_subheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('season_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='heading',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subheading',
            name='title',
        ),
        migrations.AddField(
            model_name='heading',
            name='code',
            field=models.CharField(default=12, max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subheading',
            name='code',
            field=models.CharField(default=12, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heading',
            name='season',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='customs.season'),
            preserve_default=False,
        ),
    ]
