# Generated by Django 5.1.3 on 2025-01-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0007_season_remove_heading_title_remove_subheading_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hscode',
            name='subheading',
        ),
        migrations.AddField(
            model_name='hscode',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hscodes', to='customs.heading'),
        ),
        migrations.DeleteModel(
            name='SubHeading',
        ),
    ]
