# Generated by Django 5.1.3 on 2025-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0008_remove_hscode_subheading_hscode_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='heading_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
