# Generated by Django 5.1.3 on 2025-01-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0009_heading_heading_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='code_seasons', to='customs.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hscode',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hscodes', to='customs.heading'),
        ),
    ]
