# Generated by Django 5.1.3 on 2025-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0010_hscode_season_alter_hscode_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shart', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hscode',
            name='import_duty_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
