# Generated by Django 5.1.3 on 2025-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0012_rename_shart_commercial_condition_commercial_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='title',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
