# Generated by Django 5.1.3 on 2025-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0013_commercial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
