# Generated by Django 5.1.3 on 2025-01-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0014_season_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
