# Generated by Django 5.1.3 on 2025-01-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0015_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='rule_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
