# Generated by Django 5.1.3 on 2025-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0016_commercial_rule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
