# Generated by Django 5.1.3 on 2025-01-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0017_alter_tag_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hscode',
            options={'ordering': ['-code']},
        ),
        migrations.AlterField(
            model_name='hscode',
            name='customs_duty_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='import_duty_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
