# Generated by Django 5.1.3 on 2025-01-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0018_alter_hscode_options_alter_hscode_customs_duty_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscode',
            name='customs_duty_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='profit',
            field=models.CharField(max_length=255),
        ),
    ]
