# Generated by Django 5.1.3 on 2025-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0020_alter_commercial_condition_alter_commercial_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscode',
            name='commercials',
            field=models.ManyToManyField(blank=True, to='customs.commercial'),
        ),
    ]
