# Generated by Django 5.1.3 on 2025-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
