# Generated by Django 5.1.3 on 2025-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_costumer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
