# Generated by Django 5.1.3 on 2025-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_costumer_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='customer_birthday',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
