# Generated by Django 5.1.3 on 2025-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_costumer_customer_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='customer_birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
