# Generated by Django 5.1.3 on 2025-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_costumer_customer_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='national_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
