# Generated by Django 5.1.3 on 2025-02-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetemplate',
            old_name='description_position',
            new_name='goods_start_position',
        ),
        migrations.RenameField(
            model_name='imagetemplate',
            old_name='quantity_position',
            new_name='means_of_transport_position',
        ),
        migrations.AddField(
            model_name='imagetemplate',
            name='goods_line_height',
            field=models.IntegerField(default=11231),
            preserve_default=False,
        ),
    ]
