# Generated by Django 5.1.3 on 2025-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_description_position_imagetemplate_goods_start_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetemplate',
            old_name='goods_start_position',
            new_name='description_position',
        ),
        migrations.AddField(
            model_name='imagetemplate',
            name='hscode_position',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetemplate',
            name='number_of_invoices_position',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetemplate',
            name='quantity_position',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
