# Generated by Django 5.1.3 on 2025-02-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_goods_start_position_imagetemplate_description_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetemplate',
            name='goods_start_position',
            field=models.CharField(default='100,300', help_text='X,Y coordinate for the initial line of goods', max_length=255),
        ),
    ]
