# Generated by Django 5.1.3 on 2025-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_imagetemplate_goods_start_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetemplate',
            name='font_size',
            field=models.IntegerField(default=20),
        ),
    ]
