# Generated by Django 5.1.3 on 2025-02-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_imagetemplate_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_card_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_address', models.TextField(max_length=2000)),
                ('seller_refrence', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_country', models.CharField(blank=True, max_length=55, null=True)),
                ('seller_bank_name', models.CharField(blank=True, max_length=55, null=True)),
                ('seller_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_iban', models.CharField(blank=True, max_length=55, null=True)),
                ('seller_swift', models.CharField(blank=True, max_length=55, null=True)),
                ('seller_seal', models.ImageField(upload_to='seals/')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.seller')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.invoice')),
            ],
        ),
    ]
