# Generated by Django 5.1.3 on 2025-02-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_buyer_seller_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_country',
            field=models.CharField(default=12134, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='freight_charges',
            field=models.IntegerField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_currency',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=1234, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_card_number',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_seal',
            field=models.ImageField(blank=True, null=True, upload_to='seals/'),
        ),
    ]
