# Generated by Django 5.1.3 on 2025-02-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_buyer_buyer_country_invoice_freight_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_logo',
            field=models.ImageField(blank=True, null=True, upload_to='seals/'),
        ),
    ]
