# Generated by Django 5.1.3 on 2025-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_seller_seller_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='partial_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='relevant_location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='standard',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_of_delivery',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_of_payment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_gw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_nw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='commodity_code',
            field=models.IntegerField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gw_kg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='nw_kg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='origin',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
