# Generated by Django 5.1.3 on 2025-02-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_invoice_partial_shipment_invoice_relevant_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='pack',
            field=models.IntegerField(default=1),
        ),
    ]
