# Generated by Django 5.1.3 on 2025-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_invoiceitem_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_pack',
            field=models.IntegerField(default=0),
        ),
    ]
