# Generated by Django 5.1.3 on 2025-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_invoice_total_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='U', max_length=55),
        ),
    ]
