# Generated by Django 5.1.3 on 2025-02-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_invoiceitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_gw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_nw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='gw_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='nw_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
