# Generated by Django 5.1.3 on 2025-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_invoice_total_gw_alter_invoice_total_nw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country_of_origin',
            field=models.CharField(default=1122, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='means_of_transport',
            field=models.CharField(default=1123, max_length=50),
            preserve_default=False,
        ),
    ]
