# Generated by Django 5.1.3 on 2025-02-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_invoice_country_of_origin_invoice_means_of_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='port_of_loading',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
