# Generated by Django 5.1.3 on 2025-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_invoice_port_of_loading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='partial_shipment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_of_payment',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_refrence',
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_address',
            field=models.CharField(default=1234, max_length=555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_tel',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
    ]
