# Generated by Django 5.1.3 on 2025-02-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_buyer_buyer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
