# Generated by Django 5.1.3 on 2025-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_invoice_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(max_length=1555),
        ),
    ]
