# Generated by Django 5.1.3 on 2025-02-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('proforma_invoice_date', models.DateField()),
                ('proforma_invoice_id', models.CharField(max_length=50, unique=True)),
                ('proforma_invoice_number', models.CharField(max_length=50)),
                ('proforma_freight_charges', models.IntegerField(max_length=50)),
                ('proforma_invoice_currency', models.CharField(max_length=50)),
                ('terms_of_delivery', models.CharField(max_length=50)),
                ('terms_of_payment', models.CharField(max_length=50)),
                ('relevant_location', models.CharField(max_length=50)),
                ('means_of_transport', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('port_of_loading', models.CharField(max_length=50)),
                ('total_gw', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_nw', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1555)),
                ('quantity', models.IntegerField(default=1)),
                ('commodity_code', models.IntegerField(max_length=9)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='U', max_length=55)),
                ('nw_kg', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('gw_kg', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('origin', models.CharField(max_length=55)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.proformainvoice')),
            ],
        ),
    ]
