# Generated by Django 5.1.3 on 2025-02-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_proformainvoice_proformainvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='relevant_location',
            field=models.CharField(max_length=555),
        ),
    ]
