# Generated by Django 5.1.3 on 2025-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_invoice_relevant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='country_of_origin',
            field=models.CharField(max_length=555),
        ),
    ]
