# Generated by Django 5.1.3 on 2025-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_invoice_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='partial_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='standard',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='country_of_origin',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='relevant_location',
            field=models.CharField(max_length=555),
        ),
    ]
