# Generated by Django 5.1.3 on 2025-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_proformainvoice_partial_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='port_of_loading',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='port_of_loading',
            field=models.CharField(max_length=555),
        ),
    ]
