# Generated by Django 5.1.3 on 2025-03-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_costumer_customer_address'),
        ('documents', '0024_alter_invoice_port_of_loading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounts.costumer'),
        ),
    ]
