# Generated by Django 5.1.3 on 2025-03-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_remove_proformainvoice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='proforma_invoice_exp_date',
            field=models.DateField(default="2025-01-02"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='proforma_freight_charges',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
