# Generated by Django 5.1.3 on 2025-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_proformainvoice_proforma_invoice_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='customer_tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
