# Generated by Django 5.1.3 on 2025-03-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_proformainvoice_customer_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
