# Generated by Django 5.1.3 on 2025-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_invoice_customer_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='freight_charges',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
        ),
    ]
