# Generated by Django 5.1.3 on 2025-03-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_alter_invoice_freight_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='customer_tel',
        ),
    ]
