# Generated by Django 5.1.3 on 2025-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_remove_proformainvoice_customer_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformainvoiceitem',
            old_name='description',
            new_name='original_description',
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='translated_description',
            field=models.TextField(blank=True, max_length=1555, null=True),
        ),
    ]
