# Generated by Django 5.1.3 on 2025-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_rename_description_proformainvoiceitem_original_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='original_description',
            field=models.TextField(blank=True, max_length=1555, null=True),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='translated_description',
            field=models.TextField(default=123, max_length=1555),
            preserve_default=False,
        ),
    ]
