# Generated by Django 5.1.3 on 2025-04-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_alter_proformainvoiceitem_original_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoiceitem',
            name='customer',
        ),
    ]
