# Generated by Django 5.1.3 on 2025-04-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage', '0042_cottage_intermediary'),
        ('documents', '0034_remove_proformainvoiceitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cottage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cottage.cottage'),
        ),
    ]
