# Generated by Django 5.1.3 on 2025-05-20 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_alter_proformainvoice_proforma'),
        ('proforma', '0029_alter_performa_prf_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proforma.performa', to_field='prfVCodeInt'),
        ),
    ]
