# Generated by Django 5.1.3 on 2025-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_invoice_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='commodity_code',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='commodity_code',
            field=models.CharField(max_length=9),
        ),
    ]
