# Generated by Django 5.1.3 on 2025-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_alter_invoiceitem_commodity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
    ]
