# Generated by Django 5.1.3 on 2025-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_alter_proformainvoiceitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
    ]
