# Generated by Django 5.1.3 on 2025-07-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_alter_invoiceitem_unit_price'),
        ('proforma', '0031_performa_remaining_freight_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='proforma.performa', to_field='prfVCodeInt'),
        ),
    ]
