// src/actions/actionTypes.js

// Cottages Action Types
export const FETCH_COTTAGES_REQUEST = 'FETCH_COTTAGES_REQUEST';
export const FETCH_COTTAGES_SUCCESS = 'FETCH_COTTAGES_SUCCESS';
export const FETCH_COTTAGES_FAILURE = 'FETCH_COTTAGES_FAILURE';

// Customs Declarations Action Types
export const FETCH_DECLARATIONS_REQUEST = 'FETCH_DECLARATIONS_REQUEST';
export const FETCH_DECLARATIONS_SUCCESS = 'FETCH_DECLARATIONS_SUCCESS';
export const FETCH_DECLARATIONS_FAILURE = 'FETCH_DECLARATIONS_FAILURE';

// Declaration Details Action Types
export const FETCH_DECLARATION_DETAILS_REQUEST = 'FETCH_DECLARATION_DETAILS_REQUEST';
export const FETCH_DECLARATION_DETAILS_SUCCESS = 'FETCH_DECLARATION_DETAILS_SUCCESS';
export const FETCH_DECLARATION_DETAILS_FAILURE = 'FETCH_DECLARATION_DETAILS_FAILURE';

// Goods Action Types
export const FETCH_GOODS_REQUEST = 'FETCH_GOODS_REQUEST';
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';

// Customs Duty Info Action Types
export const FETCH_CUSTOMS_DUTY_REQUEST = 'FETCH_CUSTOMS_DUTY_REQUEST';
export const FETCH_CUSTOMS_DUTY_SUCCESS = 'FETCH_CUSTOMS_DUTY_SUCCESS';
export const FETCH_CUSTOMS_DUTY_FAILURE = 'FETCH_CUSTOMS_DUTY_FAILURE';

// Save Data Action Types
export const SAVE_DATA_REQUEST = 'SAVE_DATA_REQUEST';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAILURE = 'SAVE_DATA_FAILURE';

export const SET_CUSTOMS_PARAMS = 'SET_CUSTOMS_PARAMS';
export const CLEAR_CUSTOMS_PARAMS = 'CLEAR_CUSTOMS_PARAMS';