// src/actions/actionTypes.js

// Cottages Action Types
export const FETCH_COTTAGES_REQUEST = 'FETCH_COTTAGES_REQUEST';
export const FETCH_COTTAGES_SUCCESS = 'FETCH_COTTAGES_SUCCESS';
export const FETCH_COTTAGES_FAILURE = 'FETCH_COTTAGES_FAILURE';

export const FETCH_COTTAGE_DETAILS_REQUEST = 'FETCH_COTTAGE_DETAILS_REQUEST';
export const FETCH_COTTAGE_DETAILS_SUCCESS = 'FETCH_COTTAGE_DETAILS_SUCCESS';
export const FETCH_COTTAGE_DETAILS_FAILURE = 'FETCH_COTTAGE_DETAILS_FAILURE';

// Customs Declarations Action Types
export const FETCH_DECLARATIONS_REQUEST = 'FETCH_DECLARATIONS_REQUEST';
export const FETCH_DECLARATIONS_SUCCESS = 'FETCH_DECLARATIONS_SUCCESS';
export const FETCH_DECLARATIONS_FAILURE = 'FETCH_DECLARATIONS_FAILURE';

// Declaration Details Action Types
export const FETCH_DECLARATION_DETAILS_REQUEST = 'FETCH_DECLARATION_DETAILS_REQUEST';
export const FETCH_DECLARATION_DETAILS_SUCCESS = 'FETCH_DECLARATION_DETAILS_SUCCESS';
export const FETCH_DECLARATION_DETAILS_FAILURE = 'FETCH_DECLARATION_DETAILS_FAILURE';

// Goods Action Types
export const FETCH_GOODS_REQUEST = 'FETCH_GOODS_REQUEST';
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';

// Customs Duty Info Action Types
export const FETCH_CUSTOMS_DUTY_REQUEST = 'FETCH_CUSTOMS_DUTY_REQUEST';
export const FETCH_CUSTOMS_DUTY_SUCCESS = 'FETCH_CUSTOMS_DUTY_SUCCESS';
export const FETCH_CUSTOMS_DUTY_FAILURE = 'FETCH_CUSTOMS_DUTY_FAILURE';

// Save Data Action Types
export const SAVE_DATA_REQUEST = 'SAVE_DATA_REQUEST';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAILURE = 'SAVE_DATA_FAILURE';

export const UPDATE_COTTAGE_CURRENCY_PRICE_REQUEST = 'UPDATE_COTTAGE_CURRENCY_PRICE_REQUEST';
export const UPDATE_COTTAGE_CURRENCY_PRICE_SUCCESS = 'UPDATE_COTTAGE_CURRENCY_PRICE_SUCCESS';
export const UPDATE_COTTAGE_CURRENCY_PRICE_FAILURE = 'UPDATE_COTTAGE_CURRENCY_PRICE_FAILURE';

export const SET_CUSTOMS_PARAMS = 'SET_CUSTOMS_PARAMS';
export const CLEAR_CUSTOMS_PARAMS = 'CLEAR_CUSTOMS_PARAMS';

// Save Multiple Declarations Actions

export const SAVE_MULTIPLE_DECLARATIONS_REQUEST = 'SAVE_MULTIPLE_DECLARATIONS_REQUEST';
export const SAVE_MULTIPLE_DECLARATIONS_PROGRESS = 'SAVE_MULTIPLE_DECLARATIONS_PROGRESS';
export const SAVE_MULTIPLE_DECLARATIONS_SUCCESS = 'SAVE_MULTIPLE_DECLARATIONS_SUCCESS';
export const SAVE_MULTIPLE_DECLARATIONS_FAILURE = 'SAVE_MULTIPLE_DECLARATIONS_FAILURE';



export const FETCH_PERFORMAS_REQUEST = 'FETCH_PERFORMAS_REQUEST';
export const FETCH_PERFORMAS_SUCCESS = 'FETCH_PERFORMAS_SUCCESS';
export const FETCH_PERFORMAS_FAILURE = 'FETCH_PERFORMAS_FAILURE';

export const SAVE_SELECTED_PERFORMAS_REQUEST = 'SAVE_SELECTED_PERFORMAS_REQUEST';
export const SAVE_SELECTED_PERFORMAS_SUCCESS = 'SAVE_SELECTED_PERFORMAS_SUCCESS';
export const SAVE_SELECTED_PERFORMAS_FAILURE = 'SAVE_SELECTED_PERFORMAS_FAILURE';

// src/redux/auth/authActionTypes.js

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAIL = 'TOKEN_REFRESH_FAIL';
