# Generated by Django 5.1.3 on 2024-12-10 11:39

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representi', models.CharField(max_length=255)),
                ('representor', models.CharField(max_length=255)),
                ('applicant', models.CharField(max_length=255)),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('another_deligation', models.BooleanField(default=False)),
                ('representor_dismissal', models.BooleanField(default=False)),
                ('representation_summary', models.CharField(max_length=255)),
                ('doc_number', models.BigIntegerField()),
                ('verification_code', models.BigIntegerField()),
            ],
        ),
    ]
