# Generated by Django 5.1.3 on 2024-12-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
