# Generated by Django 5.1.3 on 2024-12-10 12:11

import representation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0002_representation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
