# Generated by Django 5.1.3 on 2024-12-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0003_alter_representation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
