# Generated by Django 5.1.3 on 2024-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0004_alter_representation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
