# Generated by Django 5.1.3 on 2024-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0005_alter_representation_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='end_date',
            field=models.DateField(),
        ),
    ]
