# Generated by Django 5.1.3 on 2024-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0006_alter_representation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='end_date',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='representation',
            name='start_date',
            field=models.CharField(max_length=55),
        ),
    ]
