# Generated by Django 5.1.3 on 2024-12-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0007_alter_representation_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('check_code', models.BigIntegerField(unique=True)),
                ('date', models.CharField(max_length=255)),
                ('value', models.BigIntegerField()),
                ('issued_for', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
            ],
        ),
    ]
