# Generated by Django 5.1.3 on 2024-12-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0008_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
