# Generated by Django 5.1.3 on 2024-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0009_check_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
