# Generated by Django 5.1.3 on 2024-12-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0010_check_is_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='is_payed',
            new_name='is_paid',
        ),
    ]
