# Generated by Django 5.1.3 on 2025-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0011_rename_is_payed_check_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representation',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='representation',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='doc_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
