# Generated by Django 5.1.3 on 2025-01-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0012_alter_representation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representation',
            options={'ordering': ['-id']},
        ),
    ]
