# Generated by Django 5.1.3 on 2025-01-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0013_alter_representation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-id']},
        ),
    ]
