# Generated by Django 5.1.3 on 2025-05-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_costumer_customer_birthday_and_more'),
        ('representation', '0014_alter_check_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='Costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costumer'),
        ),
    ]
