# Generated by Django 5.1.3 on 2025-05-24 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_costumer_customer_birthday_and_more'),
        ('representation', '0015_representation_costumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='Costumer',
        ),
        migrations.AlterField(
            model_name='representation',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='accounts.costumer'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='representi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations_as_principal', to='accounts.costumer'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='representor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations_as_attorney', to='accounts.costumer'),
        ),
    ]
