# Generated by Django 5.1.3 on 2025-05-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_costumer_customer_birthday'),
        ('representation', '0016_remove_representation_costumer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='representi',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='representor',
        ),
        migrations.AddField(
            model_name='representation',
            name='representi',
            field=models.ManyToManyField(blank=True, related_name='representations_as_principal', to='accounts.costumer'),
        ),
        migrations.AddField(
            model_name='representation',
            name='representor',
            field=models.ManyToManyField(blank=True, related_name='representations_as_attorney', to='accounts.costumer'),
        ),
    ]
