# Generated by Django 5.1.3 on 2025-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0017_remove_representation_representi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='end_date',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
