# Generated by Django 5.1.3 on 2025-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0018_alter_representation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='doc_number',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='verification_code',
            field=models.CharField(),
        ),
    ]
